language: python
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - secure: aRIiTxYYmuB2zjoCcHA6u/kwW7Jnb3lvhRlO5CHRorOVW08mHURwEjJ8TqzMLOSfedAbrSMrWK+krwCnJ1IzuT6Q3h/mPlFD2bDWasrq2UeKMNHvpwZ5qzMOLsMiZxJrVR3B3cvWiuZACqEG+P/7oug1QFBYGoqHzitTDEv+5PeMwF/5e4jMKP5k3XhLGHgtwKD2nDrhuvejMyUksBh/diu3nS9FKnzKp3oeJAaB4xTZTdMXnuQRfcYRU8N89xRonG+YLB6zzTlUyFTtUJJF0yTkVyYpSEj2h+n1JaZsEnk0Q8e+Pb90mV3M3cxGphuc2YS9PuFF8OIFuajS2gSLQOahD//k3qWnmiZq7JUjMi/B9uSbh/xno4FlowO5ECcaIwEUzMRYgKrO3K6TrRFg5bQY6i0/OnpoI+kavbwJSnCIHnyhU0AwcM7zsohagQ35D11Z++7CqH2FdY5egzxIGIw5MIBgkcLN/B+Kge5RDqOrQdpbV7fRTN+zXNvNF+vZKiYwXDA95ZDeMfdw+cwAkinS+9y2k2WgdZQt4Q2HHpIVQoWVXs0vVIxsSXG5t2khQi4lcJh3DLmJZJ0lZPGvUZAP8kDyYrnv+KMtB8DpPK84/9IY3AOas77PPKr4Ds1ir0GqkWbzAdM3836Zgw9Uwb6Ic94fv/wMsnqn6lNQcz0=
  - secure: DSeUa/stfRHtOnR1esJGFv29BdXUrcFPBd98daxpSsYRhGjCl4dkvQdkTooZE/jK0PKunGlBLL9ATGOGcoqN0QLn7KNSZ7wSLj1JPlD0DczjzxMx2FoQK9BbcD+9Y0kbMRRsroGBHVtr5pPY6mFv7APGAxni0cCX4eO/qUQEQiTR9bL1qmZfjwdEg+lpsjrzp2nKupH4YiHEzbqAj3JFGPXyCwX0/EU32iIaP5vBJCX1RXRNniZEyiqRFTb5dlZTInoxfPttD+WceJ9w5aqbaDSZ007oqvwCZDRVl5aFBjzxhkDyXNh0Pp16PN3b7dkaA/Pe7CoA/zezOM/YRyimHTkonFMmEUquuqvfcF2wfLTM2AjcL9322hOJqlGAsMB9XDpRyYLQGAV1HkEGJR1BDUI4F3JqSp5K8htCaq3OXoDOypSWpiNQZZIQvUYtXTS9jeF34K53qvviHXsaGuLzs1Q4f0aSMYBiVUHkYzDC+EuXlbfXkB1eVMTiJycFQsp/5Q7ACj7d/hI3M2RFKaDXcVsesEY14ckmMVVG9EKWXOuQOX2jWEpdWhesulEpZraJSyIAG3Nibda7/BZr9Aq5cLDInbJ7pjaXpZw/VJ1pZ/dRAIh5kc8bZ0gc/EVM4CAgClrOg7yEvbT584hbBr+0Qi7gq8Rp0x7HrEJm0OGKW20=
python:
- 2.7
branches:
  only:
  - master
install:
- pip install awscli
- pip install yamllint
script:
- yamllint .
- if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then find . -type f -name '*.y?ml' -printf
  '%P\n' | while read file; do set -ex && aws s3 cp "$file" "s3://cf-templates-depost/$TRAVIS_PULL_REQUEST_BRANCH/$file"
  && aws cloudformation validate-template --template-url "https://s3.amazonaws.com/cf-templates-depost/$TRAVIS_PULL_REQUEST_BRANCH/$file"
  > /dev/null; done; fi
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  find . -type f -name '*.y?ml' -printf '%P\n' | while read file; do set -ex && aws
  s3 cp "$file" "s3://cf-templates-depost/$TRAVIS_BUILD_NUMBER/$file" && aws cloudformation
  validate-template --template-url "https://s3.amazonaws.com/cf-templates-depost/$TRAVIS_BUILD_NUMBER/$file"
  > /dev/null; done; fi
after_success:
- if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then aws s3 rm --recursive s3://cf-templates-depost/$TRAVIS_PULL_REQUEST_BRANCH;
  fi
