---
language: python
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - secure: RTchYTeKf3YVgGT+DiAwUz0uEASS4kwibU4AHL7f3oVItxhO2IULNDtmNldkhZIqkK5/JWmUceN29hIseWGGhNOBpRN9+nqGlFNhfqZ7wYY3Z80dRWaK3YUvRqjVMQW451PXwlmYYnSc2GnX20I/QmoYHK4suuukrme948i5I0ps8bZScELyexWMGrYomFhu4oiInsERyT/oGF6ZxvSYunz0MgRUuxjLCZwiKqLrTw+4WUsJwc+FwQasI1OfhjZmrxKFdl22zRW5kLT1UMHtjf+9DaLG6Y/WtfO7U3r9BS8udPnZkMGHH88h/5LafHc3o69pNAdF1nyMr3s1stvjMTT7K4i9M4oVwhdLddu3q1OI9NocqPIAkTrY57JNzPX/nRiO9gJGJMxpPBtpiLTIHGq8rnv76Kh8U1qCn1IluldRlCAwx/fOCX6p9LUyQ7ZdAI1e59HCF4WTg0pCf5vm/v/CP+ecU+VldcmWNDn8KyLVhhZfrDn2X4Ur1zxgrCZirSZiubZiIkyl9H8A6PYXQioa7ru4tKROX6Mzefc4UMn28Y0nBGXMapEaKJa4aULh0dLqVfaB9SBMPP3W+YjklgrI9/A7lyjLqldkRfE41aPxGr6uYoGBL8wZfuldNuHcT6CnKLjvR4AJZt/IZ+zdd7I/knhjx1a3d46TRNwEd8U=
  - secure: MFDDifxbbPei88p0gR/G74lo6VYlFPn+K+XNAKrSn+vep4KzIBvm58BzfwMq9nW0Uluttlicv9ItnynSmYlOSxV17Qgqw8+Cf2UvZJwqUn+cRL6n3u5+ZzX41PrfbK6/D9vC55BavFKaiRexYJl/cb7Rrmlg8423a3IQf3LN1sbBTivV5Fc3bY4A6GjQ6POLkq1siEHR3w8dnrGFvHJGcY31MvHxxAjRTxgH5BouKy6HrZ28WXqNLEQx98rbMuw6Tdy9Ofp14A2SvVzMwlNNeMadhf68M04W6WdDmc2RZijqizWLEHfXHVSSov5p4tyS3B8+olV4pBhIsAWoWWqsB/d6k3YXrFtk+9fklLRshQ+DYtZNOgr6iI0GAI2gRQM+LU9ClGRcR5xuSueKHnMP0JTzX4kZRBh7OxYuuGTZuyPajMc/gcXe2zVIIaYuM1Ov6Ncvo3+9tWyi/v4984bzysbiO1e9mZdwMAZrHV9wb7GAR0h3XyjA0Gi8rFXhNK2D1CHeSYeBY1izomxGi8Yw6aCuO8AReU+bzuUlo0bMF3l1NaC3zWFwGza5Xjkg67TWR+750tNs7C8qt7GBMiUWPyHRPLbYfvRT0/g76Gf0GCa0PgvsJHvcK1K2Qb/z/ZMLMocjXuXuaF503xHLDw+B0utkY+X7RBB2ZD64ua9Fl5E=
python:
- 2.7
branches:
  only:
  - master
install:
- pip install awscli
- pip install yamllint
script:
- yamllint .
- if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then find . -type f -name '*.y?ml' -printf
  '%P\n' | while read file; do set -ex && aws s3 cp "$file" "s3://cf-templates-depost/$TRAVIS_PULL_REQUEST_BRANCH/$file"
  && aws cloudformation validate-template --template-url "https://s3.amazonaws.com/cf-templates-depost/$TRAVIS_PULL_REQUEST_BRANCH/$file"
  > /dev/null; done; fi
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  find . -type f -name '*.y?ml' -printf '%P\n' | while read file; do set -ex && aws
  s3 cp "$file" "s3://cf-templates-depost/$TRAVIS_BUILD_NUMBER/$file" && aws cloudformation
  validate-template --template-url "https://s3.amazonaws.com/cf-templates-depost/$TRAVIS_BUILD_NUMBER/$file"
  > /dev/null; done; fi
after_success:
- if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then aws s3 rm --recursive s3://cf-templates-depost/$TRAVIS_PULL_REQUEST_BRANCH;
  fi
