AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route 53 Hosted Zone'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Hosted Zone Parameters'
      Parameters:
      - DomainName
Parameters:
  DomainName:
    Description: 'The Domain Name'
    Type: String
    Default: ''
Conditions:
  HasName: !Not [!Equals [!Ref DomainName, '']]
Resources:
  DNS:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig:
        Comment: !Join [ ' ', [ 'Public DNS Zone for', !Ref DomainName ] ]
      Name: !Ref DomainName
      HostedZoneTags:
      -
        Key: 'Domain'
        Value: !Ref DomainName
Outputs:
  ZoneId:
    Value: !Ref DNS
    Description: 'Hosted Zone Id'
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneId'

  DomainName:
    Value: !Ref DomainName
    Description: 'Domain'
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'
