---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudTrail across all regions with support for multiple accounts'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'CloudTrail Parameters'
      Parameters:
      - CloudWatchLogsRetentionInDays
      - CloudTrailBucketName
    - Label:
        default: 'CloudTrail Multi Account Parameters'
      Parameters:
      - AdditionalAccounts

Parameters:
  CloudWatchLogsRetentionInDays:
    Description: 'The number of days log events are kept in CloudWatch Logs'
    Type: Number
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  CloudTrailBucketName:
    Description: 'The name of the CloudTrail bucket to use or leave empty to create a new bucket'
    Type: String
    MaxLength: 64
  AdditionalAccounts:
    Description: 'The account ids which are allowed to write to the CloudTrail bucket'
    Type: CommaDelimitedList
Conditions:
  NeedsNewCloudTrailBucket: !Equals [!Ref CloudTrailBucketName, ""]
Resources:
  TrailBucket:
    Condition: NeedsNewCloudTrailBucket
    Type: 'AWS::S3::Bucket'
    Properties: {}
    DeletionPolicy: Retain
  TrailBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref TrailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AWSCloudTrailAclCheck
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 's3:GetBucketAcl'
          Resource: !Sub 'arn:aws:s3:::${TrailBucket}'
        - Sid: AWSCloudTrailWrite
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 's3:PutObject'
          # Extend this as required for the number of account ids. By default the current account is added
          Resource:
            - !Sub 'arn:aws:s3:::${TrailBucket}/AWSLogs/${AWS::AccountId}/*'
          Condition:
            StringEquals:
              's3:x-amz-acl': 'bucket-owner-full-control'

  TrailLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      RetentionInDays: !Ref CloudWatchLogsRetentionInDays

  TrailLogGroupRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - 'cloudtrail.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
      -
        PolicyName: 'cloudtrail-policy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          -
            Effect: Allow
            Action: 'logs:CreateLogStream'
            Resource: !Sub '${TrailLogGroup.Arn}'
          -
            Effect: Allow
            Action: 'logs:PutLogEvents'
            Resource: !Sub '${TrailLogGroup.Arn}'

  TrailTopic:
    Type: 'AWS::SNS::Topic'
    Properties: {}
  TrailTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
        - Sid: AWSCloudTrailSNSPolicy
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Resource: !Ref TrailTopic
          Action: 'sns:Publish'
      Topics:
      - !Ref TrailTopic

  # Create KMS Key for CloudTrail
  TrailKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: 'CloudTrail KMS Key'
      Enabled: true
      EnableKeyRotation: false
      KeyPolicy:
        Version: "2012-10-17"
        Id: "key-default-1"
        Statement:
          -
            Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal:
              AWS: [
                "arn:aws:iam::750644679422:root",
                "arn:aws:iam::750644679422:user/bhavikk"
              ]
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
          -
            Sid: "Allow CloudTrail to describe the key"
            Effect: "Allow"
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action:
              - "kms:DescribeKey"
            Resource: "*"
          -
            Sid: "Allow CloudTrail to encrypt logs"
            Effect: "Allow"
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action:
              - "kms:GenerateDataKey*"
            Resource: "*"
            Condition:
              StringLike:
                kms:EncryptionContext:aws:cloudtrail:arn:
                  - !Sub 'arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*'

  # Create the CloudTrail
  Trail:
    DependsOn:
    - TrailBucketPolicy
    - TrailTopicPolicy
    - TrailKey
    Type: 'AWS::CloudTrail::Trail'
    Properties:
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true
      IsLogging: true
      IsMultiRegionTrail: true
      S3BucketName: !Ref TrailBucket
      CloudWatchLogsLogGroupArn: !Sub '${TrailLogGroup.Arn}'
      CloudWatchLogsRoleArn: !Sub '${TrailLogGroupRole.Arn}'
      SnsTopicName: !Sub '${TrailTopic.TopicName}'
      KMSKeyId: !Sub '${TrailKey.Arn}'
