---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a public bucket and a single user with write access.'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'S3 Parameters'
      Parameters:
      - BucketName

Parameters:
  BucketName:
    Description: 'Optional name of the bucket.'
    Type: String
    Default: ''

Conditions:
  HasBucketName: !Not [!Equals [!Ref BucketName, '']]

Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !If [HasBucketName, !Ref BucketName, !Ref 'AWS::NoValue']
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 7
          Status: Enabled

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Principal: '*'
          Action: 's3:GetObject'
          Effect: Allow
          Resource: !Sub '${Bucket.Arn}/*'

  BuildUser:
    Type: "AWS::IAM::User"

  BuildUserPolicy:
    Type: 'AWS::IAM::Policy'
    DependsOn: BuildUser
    Properties:
      PolicyName: !Sub '${AWS::StackName}-BuildUser-Policy'
      Users:
      - !Ref BuildUser
      PolicyDocument:
        Statement:
        -
          Effect: 'Allow'
          Action:
          - 's3:ListAllMyBuckets'
          Resource: 'arn:aws:s3:::*'
        -
          Effect: 'Allow'
          Action:
          - 's3:CreateBucket'
          - 's3:PutObject'
          Resource:
          - !Join ["", ["arn:aws:s3:::", !Ref Bucket]]
        -
          Effect: 'Allow'
          Action:
          - 's3:CreateBucket'
          - 's3:PutObject'
          Resource:
          - !Join ["", ["arn:aws:s3:::", !Ref Bucket, "/*"]]
        -
          Effect: 'Allow'
          Action:
          - 'cloudformation:ValidateTemplate'
          Resource:
          - '*'

  BuildCredentials:
    Type: 'AWS::IAM::AccessKey'
    DependsOn: BuildUser
    Properties:
      UserName: !Ref BuildUser

Outputs:
  Bucket:
    Description: 'S3 Bucket with the website'
    Value: !Ref Bucket
  UserNameBuildUser:
    Description: 'Name of the Build User'
    Value: !Ref BuildUser
  AccessKeyBuildUser:
    Description: 'The access key for the build user'
    Value: !Ref BuildCredentials
  SecretAccessKeyBuildUser:
    Description: 'The secret access key for build user'
    Value: !GetAtt BuildCredentials.SecretAccessKey
