---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to create administration group with the ability to assume administrator access in other accounts'
Resources:
  AssumeAdminAccessRolePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "This policy allows users to assume the administrator access"
      ManagedPolicyName: AdminAccessPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        # Allow administrators to assume AdminAccessRole in any account
        -
          Effect: "Allow"
          Action:
          - "sts:AssumeRole"
          Resource:
          - "arn:aws:iam::*:role/AdminAccessRole"

  AdminGroup:
    Type: "AWS::IAM::Group"
    Properties:
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AdministratorAccess"
      - !Ref AssumeAdminAccessRolePolicy

Outputs:
  AdminGroupName:
    Description: "The Administrator Group Name"
    Value: !Ref AdminGroup

  AdminGroupArn:
    Description: "The Administrator Group ARN"
    Value: !GetAtt AdminGroup.Arn
    Export:
      Name: !Sub '${AWS::StackName}-AdminUserGroup'
