---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Allow cross account billing access'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Account Parameters'
      Parameters:
      - TrustedAccount

Parameters:
  TrustedAccount:
    Description: 'The account which users will be allowed to assume the roles'
    Type: String

Resources:
  BillingRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        -
          Effect: Allow
          Principal:
            AWS:
            - !Join ['', ['arn:aws:iam::', !Ref TrustedAccount, ':root']]
          Action:
          - 'sts:AssumeRole'
          Condition:
            BoolIfExists:
              aws:MultiFactorAuthPresent: true

      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/job-function/Billing
      RoleName: 'BillingAccessRole'

Outputs:
  BillingRoleName:
    Description: 'The name of the role.'
    Value: !Ref BillingRole

  BillingRoleArn:
    Description: 'The Arn of the role.'
    Value: !GetAtt BillingRole.Arn
