---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to create engineering group with the ability to assume access in create resources cross accounts'
Resources:
  AssumeEngineerAccessRolePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "This policy allows users to assume the administrator access"
      ManagedPolicyName: EngineerAccessPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        # Allow Finance users to assume EngineerAccessRole in any account
        -
          Effect: "Allow"
          Action:
          - "sts:AssumeRole"
          Resource:
          - "arn:aws:iam::*:role/EngineerAccessRole"

  EngineerGroup:
    Type: "AWS::IAM::Group"
    Properties:
      ManagedPolicyArns:
      - !Ref AssumeEngineerAccessRolePolicy

Outputs:
  EngineerGroupName:
    Description: "The Engineer Group Name"
    Value: !Ref EngineerGroup

  EngineerGroupArn:
    Description: "The Engineer Group ARN"
    Value: !GetAtt EngineerGroup.Arn
    Export:
      Name: !Sub '${AWS::StackName}-EngineerUserGroup'
