---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Allow engineers to have cross account admin access'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Account Parameters'
      Parameters:
      - TrustedAccount

Parameters:
  TrustedAccount:
    Description: 'The account which users will be allowed to assume the roles'
    Type: String

Resources:
  EngineerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                  - !Join ['', [ 'arn:aws:iam::', !Ref TrustedAccount, ':root' ] ]
            Action:
              - 'sts:AssumeRole'
            Condition:
              BoolIfExists:
                aws:MultiFactorAuthPresent: true
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: 'EngineerAccessRole'


Outputs:
  EngineerRoleName:
    Description: 'The name of the role.'
    Value: !Ref EngineerRole

  EngineerRoleArn:
    Description: 'The Arn of the role.'
    Value: !GetAtt EngineerRole.Arn
