---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Allow cross account security audit access'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Account Parameters'
      Parameters:
      - TrustedAccount

Parameters:
  TrustedAccount:
    Description: 'The account which users will be allowed to assume the roles'
    Type: String

Resources:
  SecurityAuditPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "This policy allows users custom security audit policies"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Allow security users to assume SecurityAuditAccessRole in any account
          -
            Effect: "Allow"
            Action:
              - "cloudtrail:LookupEvents"
            Resource:
              - "*"

  SecurityAuditRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                  - !Join ['', [ 'arn:aws:iam::', !Ref TrustedAccount, ':root' ] ]
            Action:
              - 'sts:AssumeRole'
            Condition:
              BoolIfExists:
                aws:MultiFactorAuthPresent: true
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - !Ref SecurityAuditPolicy
      RoleName: 'SecurityAuditAccessRole'


Outputs:
  SecurityAuditRoleName:
    Description: 'The name of the role.'
    Value: !Ref SecurityAuditRole

  SecurityAuditRoleArn:
    Description: 'The Arn of the role.'
    Value: !GetAtt SecurityAuditRole.Arn
