---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to create security group with the ability to assume security audit access in other accounts'
Resources:
  AssumeSecurityAuditAccessRolePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "This policy allows users to assume the security audit access"
      ManagedPolicyName: SecurityAuditAccessPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        # Allow security users to assume SecurityAuditAccessRole in any account
        -
          Effect: "Allow"
          Action:
          - "sts:AssumeRole"
          Resource:
          - "arn:aws:iam::*:role/SecurityAuditAccessRole"

  SecurityAuditPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "This policy allows users custom security audit policies"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        # Allow security users to assume SecurityAuditAccessRole in any account
        -
          Effect: "Allow"
          Action:
          - "cloudtrail:LookupEvents"
          Resource:
          - "*"
  SecurityGroup:
    Type: "AWS::IAM::Group"
    Properties:
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/SecurityAudit"
      - !Ref AssumeSecurityAuditAccessRolePolicy
      - !Ref SecurityAuditPolicy

Outputs:
  SecurityGroupName:
    Description: "The Security Group Name"
    Value: !Ref SecurityGroup

  SecurityGroupArn:
    Description: "The Security Group ARN"
    Value: !GetAtt SecurityGroup.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SecurityUserGroup'
